//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyLoginLog
    {
        public int SupplyLoginLogID { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public string PurcharseNo { get; set; }
        public string LoginIP { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
    }
}
