//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOperationDetail
    {
        public int SupplyOperationDetailID { get; set; }
        public int SupplyOperationID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string ChangeContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
