//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPostData
    {
        public int SupplyPostDataID { get; set; }
        public string PurchaseNo { get; set; }
        public string ExpressNo { get; set; }
        public string LogiticsCompany { get; set; }
        public string LocalIP { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
