//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyCategory
    {
        public int SupplyCategoryID { get; set; }
        public int SupplyID { get; set; }
        public string CategoryCode { get; set; }
        public bool IsEnable { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdTime { get; set; }
    }
}
