//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyAccount
    {
        public int SupplyAccountID { get; set; }
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdUser { get; set; }
        public System.DateTime UpdTime { get; set; }
        public string Email { get; set; }
        public string SupplierAccount { get; set; }
        public Nullable<int> UserType { get; set; }
    }
}
